[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "php artisan migrate --force && php artisan optimize && php-fpm -D && nginx -g 'daemon off;'"
healthcheckPath = "/up"
healthcheckTimeout = 60